name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Download JUnit 3
      run: |
        wget https://repo1.maven.org/maven2/junit/junit/3.8.2/junit-3.8.2.jar
    - name: Compile all Java files
      run: |
        find . -name "*.java" > sources.txt
        javac -cp junit-3.8.2.jar -d bin @sources.txt
    - name: Find all test classes
      run: |
        find bin -name "*.class" | sed 's|bin/||;s|/|.|g;s|.class||' > test_classes.txt
    - name: Run all test classes with JUnit 3
      run: |
        while read -r test_class; do
          test_file=$(find . -name "$(basename $test_class).java")
          if grep "@Test" $test_file; then
            if ! java -cp bin:junit-3.8.2.jar junit.textui.TestRunner $test_class; then
              echo "Test failed: $test_class"
              exit 1
            fi
          fi
        done < test_classes.txt
# hola
