name: Java 19 Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Download JUnit 4.12
        run: |
          curl -o $GITHUB_WORKSPACE/junit-4.12.jar https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar

      - name: Compile program
        run: |
          javac -d $GITHUB_WORKSPACE/out $GITHUB_WORKSPACE/src/*.java

      - name: Find test classes
        run: |
          find $GITHUB_WORKSPACE/out -type f -name "*.class" | grep -E '.*Test.*' | sed 's|.*/\(.*\)\.class$|\1|' > $GITHUB_WORKSPACE/test_classes.txt

      - name: Run tests
        run: |
          java -cp "$GITHUB_WORKSPACE/out:$GITHUB_WORKSPACE/junit-4.12.jar" org.junit.runner.JUnitCore $(cat $GITHUB_WORKSPACE/test_classes.txt)
