name: Java 19 Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'

      - name: Create lib directory
        run: mkdir $GITHUB_WORKSPACE/lib

      - name: Download JUnit 3.8.2
        run: |
          curl -o $GITHUB_WORKSPACE/lib/junit-3.8.2.jar https://repo1.maven.org/maven2/junit/junit/3.8.2/junit-3.8.2.jar

      - name: Compile program
        run: |
          javac -d $GITHUB_WORKSPACE/out/classes -sourcepath $GITHUB_WORKSPACE/src -classpath $GITHUB_WORKSPACE/lib/junit-3.8.2.jar $GITHUB_WORKSPACE/src/*.java

      - name: Find test source files
        run: find $GITHUB_WORKSPACE/Test -name "*.java" > test_sources.txt

      - name: Compile tests
        run: |
          javac -d $GITHUB_WORKSPACE/out/test -sourcepath $GITHUB_WORKSPACE/Test -classpath $GITHUB_WORKSPACE/out/classes:$GITHUB_WORKSPACE/lib/junit-3.8.2.jar @$GITHUB_WORKSPACE/test_sources.txt

      - name: Run tests
        run: |
          java -classpath $GITHUB_WORKSPACE/out:test:$GITHUB_WORKSPACE/lib/junit-3.8.2.jar junit.textui.TestRunner test.Tests
