name: Java 19 Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
          
      - name: Compile and run tests
        run: |
          javac -d  $GITHUB_WORKSPACE/src -sourcepath $GITHUB_WORKSPACE/src $(find $GITHUB_WORKSPACE/src -name '*.java')
          java -cp  $GITHUB_WORKSPACE/Test/testing/Test.java
