name: Java CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'

    - name: Run tests
      run: |
        java -cp "out/:out/*" org.junit.runner.JUnitCore Tests.Tests
