name: Java CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: 'adopt@1.19'
        distribution: 'jdk'
        architecture: 'x64'

    - name: Run tests
      run: |
        java -cp "path/to/classes:path/to/classes/*" org.junit.runner.JUnitCore com.example.tests.TestClass
