name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Compile all Java files
      run: |
        find . -name "*.java" > sources.txt
        javac -d bin @sources.txt
    - name: Run tests
      run: java -cp bin Tests
