name: Java CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Download JUnit 3
      run: |
        wget https://repo1.maven.org/maven2/junit/junit/3.8.2/junit-3.8.2.jar
    - name: Compile all Java files
      run: |
        find . -name "*.java" > sources.txt
        javac -cp junit-3.8.2.jar -d bin @sources.txt
    - name: Find Tests class
      run: |
        TEST_CLASS=$(find bin -name "Tests.class" | sed 's|bin/||;s|/|.|g;s|.class||')
        echo "TEST_CLASS=$TEST_CLASS" >> $GITHUB_ENV
    - name: Run Tests class with JUnit 3
      run: java -cp bin:junit-3.8.2.jar:res junit.textui.TestRunner $TEST_CLASS
